# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 16:47
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(verbose_name='created at')),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('pin_url', models.CharField(max_length=250)),
                ('source_url', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pinpics')),
                ('color', models.CharField(max_length=7)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pinapp.Board')),
            ],
        ),
    ]
