# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='note',
            field=models.TextField(default='', help_text='The user-entered description of the Pin.'),
        ),
        migrations.AlterField(
            model_name='board',
            name='board_id',
            field=models.CharField(help_text='The unique string of numbers and letters that identifies the board on Pinterest.', max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date the user created the board.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(help_text='The name of the board.', max_length=50),
        ),
        migrations.AlterField(
            model_name='pin',
            name='board',
            field=models.ForeignKey(blank=True, help_text='The board that the Pin is on.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pinapp.Board'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='color',
            field=models.CharField(help_text='The dominant color of the Pin\u2019s image in hex code format.', max_length=7),
        ),
        migrations.AlterField(
            model_name='pin',
            name='created_at',
            field=models.DateTimeField(help_text='The date the Pin was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='image',
            field=models.ImageField(help_text='The Pin\u2019s image. The default response returns the image\u2019s URL, width and height.', upload_to='pinpics'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_id',
            field=models.CharField(help_text='The unique string of numbers and letters that identifies the Pin on Pinterest.', max_length=50),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_url',
            field=models.CharField(help_text='The URL of the Pin on Pinterest. Should be more than 2000 to be sure.', max_length=250),
        ),
        migrations.AlterField(
            model_name='pin',
            name='source_url',
            field=models.CharField(help_text='The URL of the webpage where the Pin was created. Should be more than 2000 to be sure.', max_length=250),
        ),
    ]
