# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-20 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinapp', '0002_auto_20160316_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the board.', max_length=50)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
            ],
            options={
                'managed': True,
                'abstract': False,
                'db_table': 'pinapp_board_translation',
                'db_tablespace': '',
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='board',
            name='name',
        ),
        migrations.AddField(
            model_name='boardtranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pinapp.Board'),
        ),
        migrations.AlterUniqueTogether(
            name='boardtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
