# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 22:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinapp', '0005_pin_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='Extra information about the Pin for Rich Pins. Includes the Pin type (e.g., article, recipe) and related information (e.g., ingredients, author).'),
        ),
        migrations.AddField(
            model_name='pin',
            name='video_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='The source data for videos, including the title, URL, provider, author name, author URL and provider name.'),
        ),
    ]
