# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinapp', '0007_pin_imported_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='imported_at',
        ),
        migrations.AddField(
            model_name='pin',
            name='sync_at',
            field=models.DateTimeField(default='2017-08-12 12:42:00', help_text='The date the Pin was synchronized.', verbose_name='synchronized at'),
            preserve_default=False,
        ),
    ]
