# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinapp', '0008_auto_20170815_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='local_note',
            field=models.TextField(default='', help_text='The local user-entered description of the Pin.'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='note',
            field=models.TextField(default='', help_text='The pinterest user-entered description of the Pin.'),
        ),
    ]
