# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinapp', '0010_pin_true_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='true_source_url',
            field=models.CharField(help_text='The true URL of the webpage where the Pin was created. Should be more than 2000 to be sure.', max_length=2000, null=True),
        ),
    ]
